#!/bin/python3

import os
import sys

def timeConversion(s):
    list1 = s.split(':')
    hh = list1[0]
    if list1[0] == '12':
        hh = '00'
    if 'AM' in list1[2]:
        meridian = list(list1[2])
        del meridian[2]
        del meridian[2]
        return(f"{hh}:{list1[1]}:{meridian[0]}{meridian[1]}")
    elif 'PM' in list1[2]:
        if list1[0] != '12':
            hh = int(list1[0]) + 12
        else:
            hh = '12'
        meridian = list(list1[2])
        del meridian[2]
        del meridian[2]
        return(f"{hh}:{list1[1]}:{meridian[0]}{meridian[1]}")

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
