#!/bin/python3



import math

import os

import random

import re

import sys



# Complete the staircase function below.

def staircase(n):



    if __name__ == '__main__':

        for i in range(1, n + 1):

            text1 = ' ' * (n - i)

            text2 = '#' * (i)

            print(text1 + text2)



n = int(input())

staircase(n)
